name: C++

on:
  push:
    branches: [master]
    paths:
    - 'cpp/**'
  workflow_dispatch:

jobs:
  run_cpp_tests:
    name: Run C++ Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/cpp
        mkdir build
        cd build
        cmake -S .. -B .
        cmake --build .

    - name: Run
      run: |
        cd $GITHUB_WORKSPACE/testing/test_images
        ./$GITHUB_WORKSPACE/cpp/build/main 6 10 ../test_glider.txt
        cd ..
        sh run_diffs.sh