name: Java

on:
  push:
    branches: [master]
    paths:
    - 'java/**'
  workflow_dispatch:

jobs:
  run_java_tests:
    name: Run Java Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/java
        mvn clean package

    - name: Run
      run: |
        cd $GITHUB_WORKSPACE/testing/test_images
        java -jar $GITHUB_WORKSPACE/java/target/main-1.0-SNAPSHOT.jar 6 10 ../test_glider.txt
        cd ..
        sh run_diffs.sh