name: Python

on:
  push:
    branches: [master]
    paths:
    - 'python/**'
  workflow_dispatch:

jobs:
  run_python_tests:
    name: Run Python Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.5'
        architecture: 'x64'

    - name: Run
      run: |
        cd $GITHUB_WORKSPACE/testing/test_images
        python ../../python/main.py 6 10 ../test_glider.txt
        cd ..
        sh run_diffs.sh